### ISSUE TITLE
llrp_manager_example: Wrong output for Device info -> Product Category

### ISSUE THREAD

**Issue by vanvught** [ETCLabs/RDMnet#16]
```
Device info:
  RDM Protocol Version: 1.0
  Device Model ID: 32552 (0x7f28)
  Product Category:
    Coarse: 127 (0x7f)
    Fine: 255 (0xff)
  Software Version ID: 1568217936 (0x5d791b50)
  DMX512 Footprint: 16
  DMX512 Personality:
    Current: 1
    Total: 1
  DMX512 Start Address: 1
  Subdevice Count: 0
  Sensor Count: 1
```

Issue is here -> https://github.com/ETCLabs/RDMnet/blob/develop/examples/llrp_manager/src/manager.cpp#L465

etcpal_upack_16b should be used with cur_ptr += 2;

**Comment by bootress** [comment]
Can you provide more detail on what's wrong with the output here? I was trying to display the "coarse" and "fine" 8-bit subfields as described in the RDM standard section 10.5.1 and table A-5.

**Comment by vanvught** [comment]
Hi Sam, my mistake. My apologize. I was reading the output as: E120_PRODUCT_CATEGORY and E120_PRODUCT_DETAIL. However, E120_PRODUCT_DETAIL is not part of the Device Info. So it is all OK.
