### ISSUE TITLE
llrp_manager_example: kLlrpCompNonRdmnet defined but not used

### ISSUE THREAD

**Issue by vanvught** [ETCLabs/RDMnet#17]
The kLlrpCompNonRdmnet is not used in https://github.com/ETCLabs/RDMnet/blob/041b8f11e76b48eba35e662f3f30010a4221faa7/examples/llrp_manager/src/manager.cpp#L907

where it is here -> https://github.com/ETCLabs/RDMnet/blob/4ab9184b01c12bf9153340c36c42c6f43e97783f/include/rdmnet/core/llrp.h#L50

Hence I am getting Unknown ->

> Handle UID           CID                                  Type            Hardware ID
> 0      7ff0:3064d9e5 9183911e-6986-40e8-a6e7-159f7cfd6251 Unknown         f4:4d:30:64:d9:e5

where I have set -> https://github.com/ETCLabs/RDMnet/blob/4ab9184b01c12bf9153340c36c42c6f43e97783f/include/rdmnet/defs.h#L242

**Comment by bootress** [comment]
Gotcha. "NON_RDMNET" was "UNKNOWN" in the previous standard draft which explains why this didn't get updated. I will fix it.
